### ISSUE TITLE
Steps to build docker image

### ISSUE THREAD

**Issue by BesPav** [austins/DiscordTranslationBot#18]
Hi, Austin!
Please, can you add description on how to build image for docker?
I have sucessfully run LibreTranslate on my Synology NAS and want to play with functions of your bot.

**Comment by austins** [comment]
@BesPav Sorry for the late reply, I didn't get any notification from GitHub.

You can run the `docker build` command like so:
```
cd ./DiscordTranslationBot
docker build -t DiscordTranslationBot .
```

Let me know if it works!

**Comment by austins** [comment]
Updated the readme with steps for Docker.
